/**
 * Gravitee.io Portal Rest API
 * API dedicated to the devportal part of Gravitee
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@graviteesource.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OAuthClientSettings { 
    clientSecret?: string;
    clientId?: string;
    redirectUris?: Array<string>;
    clientUri?: string;
    logoUri?: string;
    responseTypes?: Array<string>;
    grantTypes?: Array<string>;
    applicationType?: string;
    renewClientSecretSupported?: boolean;
}

